
debug: true

feign:
  client:
    config:
      httpbin: # @FeignClient 에서 name 값, 전역으로 설정하려면 default
        connectTimeout: 5000
        readTimeout: 2000
        loggerLevel: FULL
        errorDecoder: net.anyjava.springboot.study.feign.FeignSampleErrorDecode

logging:
  level:
    net.anyjava.springboot.study.MockHttpClient: DEBUG

