
debug: false

feign:
  client:
    config:
      default: # @FeignClient 에서 name 값, 전역으로 설정하려면 default
        connectTimeout: 5000
        readTimeout: 2000
        loggerLevel: FULL  # 해당 feign interface 가 있는 package 의 log level 이 꼭 DEBUG 여야 함.
        errorDecoder: net.anyjava.springboot.study.feign.FeignSampleErrorDecode

logging:
  level:
    net.anyjava.springboot.study.feign.MockHttpClient: DEBUG

